<a href="https://colab.research.google.com/github/Thrisha-19/Deep-Learning/blob/main/Loss_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

## Mean Absolute **Error**

In [10]:
def mae(y_predicted,y_true):
  total_error = 0
  for yp,yt in zip(y_predicted,y_true):
    total_error += abs(yp-yt)
  print("Total error is : ",total_error)
  mae = total_error/len(y_predicted)
  print("Mean Absolute Error: ", mae)
  return mae

In [11]:
mae(y_predicted,y_true)

Total error is :  2.5
Mean Absolute Error:  0.5


0.5

In [12]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [13]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [14]:
def mae_np(y_predicted,y_true):
  return np.mean(np.abs(y_predicted - y_true))

In [15]:
mae_np(y_predicted,y_true)

0.5

# Log Loss/ Binary Cross Entropy

In [17]:
np.log([0])

<ipython-input-17-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [18]:
epsilon = 1e-15

In [19]:
np.log([1e-15])

array([-34.53877639])

In [20]:
y_predicted

array([1, 1, 0, 0, 1])

In [23]:
y_predict_new = [max(i,epsilon)  for i in y_predicted]
y_predict_new

[1, 1, 1e-15, 1e-15, 1]

In [24]:
1-epsilon

0.999999999999999

In [25]:
y_predict_new = [min(i,1-epsilon) for i in y_predict_new]
y_predict_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [26]:
y_predict_new = np.array(y_predict_new)

In [27]:
np.log(y_predict_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [29]:
-np.mean(y_true*np.log(y_predict_new)+(1-y_true)*np.log(1-y_predict_new))

17.2696280766844

In [30]:
def log_loss(y_true, y_predicted):
    y_predict_new = [max(i,epsilon) for i in y_predicted]
    y_predict_new = [min(i,1-epsilon) for i in y_predict_new]
    y_predict_new = np.array(y_predict_new)
    return -np.mean(y_true*np.log(y_predict_new)+(1-y_true)*np.log(1-y_predict_new))

In [31]:
log_loss(y_true,y_predicted)

17.2696280766844